export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_FAVOURITES = "GET_FAVOURITES";
export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const DELETE_FAVOURITE = "DELETE_FAVOURITE";
export const FAVOURITES_LOADING = "FAVOURITES_LOADING";